baseurl = "https://miga.me.uk"
languageCode = "en-us"
title = "XKJC"
theme = "dimension"

[params]
    title = "Danila Migalin"
    description = "IT pathologist"
    logo = "fa-terminal"
    copyright = "XKJC"


    [[params.social]]
      medium = "Twitter"
      icon = "twitter"
      link = "https://twitter.com/beebeeep"

    [[params.social]]
      medium = "Github"
      icon = "github"
      link = "https://github.com/beebeeep"

    [[params.social]]
      medium = "Email"
      icon = "envelope-o"
      link = "mailto:me@miga.me.uk"

    [[params.social]]
      medium = "Linkedin"
      icon = "linkedin"
      link = "https://www.linkedin.com/in/danila-migalin-29499447"

    [[params.social]]
      medium = "Last.fm"
      icon = "lastfm"
      link = "http://www.last.fm/user/miga"
